# Generated by Django 5.1.4 on 2024-12-12 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
