# Generated by Django 5.1.4 on 2024-12-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_withdrawal_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('paymaya', 'PayMaya')], max_length=10),
        ),
    ]
