# Generated by Django 5.1.4 on 2024-12-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
