# Generated by Django 5.1.4 on 2024-12-10 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_delete_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='date_played',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='score',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='amount_wagered',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='amount_won',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_name',
            field=models.CharField(default='Unknown Game', max_length=100),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
