# Generated by Django 5.1.4 on 2024-12-13 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_choice_rename_placed_at_bet_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.choice'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
